### ISSUE TITLE
Implement A GitHub Actions Pipeline

### ISSUE THREAD

**Issue by xKabbe** [xKabbe/testx#2]
# Description

The project is missing some kind of pipeline in which automated tests, and probably more, can run after each commit/before merge.

Create a basic pipeline, in GitHub called `GitHub Actions`.

# Additional Context (Screenshots, Logs, ...)

## General Example

```yml
name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
```

## DeNigmA Example

```yml
name: Test React Application
run-name: ${{ github.actor }} is testing 🧪 the React Application 💻

# Controls when the action will run.
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # ID of the job
  react-jest-test:
    # Name of the job as it will be displayed in GitHub
    name: React Jest Test 🧪
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies 🪜
        run: npm ci
      - name: Run Jest Tests 🪜
        run: npm test
      - name: Post Coverage to Coveralls 🪜
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./out/coverage/lcov.info
```

## [Python Example](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python)

```yml
name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
          # default set of ruff rules with GitHub Annotations
          ruff --format=github --target-version=py37 .
      - name: Test with pytest
        run: |
          pytest
```

# Expected Actions
* [ ] Basic `GitHub Actions` functionality

# Definition of Done
* [ ] `Code` implemented or adjusted
